version: '2'
networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis-container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  myapp:
    build: .
    ports:
      - "5000:5000"
    container_name: app
    networks:
      - app-tier
